language: java
jdk:
  - oraclejdk9
before_install:
  - chmod +x gradlew
install:
  - gem install bundler
  - bundle install
notifications:
  email: false
  slack:
    secure: c6hutJjcg2xeJIY6FDB4B8f9w9YFIie0/smKJdBUbuJ9/7hq8wRsU4+M/pzwNC7MAPd28V17bgR4LeeZImhy+u8IEizweOMYFQ69SM9CA0PPes+Dtttp8SLh2BI7vxpB3V8NS/Eyi7Xf5nvY0cDSFOnMcoz2twxi9MyzPhW4htBH3v8O3eFl0P0A2WhvjvkhdJqinzLIx6SUOAOzPCPlz5od1Fx7DwBmHKUJ0YlaD6zWcgS0CeYL571AqejicmrGod9AXkQLS5y2vdbYWzSs8LYaDuZoT67Uc9KgJ3N1JNpgzjD+C0St/PqtAjs5OdL3RtdMlARaD3c4hgViPs0ebqKkBWQrV/L/8zyMGqJIZmEYvdowUxlDsdMsS9q2+2Zf/C/zi2NSc0a+ihS94q/P8cvmsZ2VO3PaPRmAmtfXzf0PCh5TmKYG4nWm5M340KdHJPK6dJX02YZATeMw7z0owT3ilKRT00anuAr8Bzv1htHmy34CEVIMl7Zt69Iw0pKQaUFFTzJN1aB6bccXmJY47CDdpATs7Ss95kRjJz1ElVc48uZsc+5khAPwd0CT/3ZkEbvuFMkechWtwpKUMb3LwqywGti5UbeUQYV9irl9Oh9tiMdrx1EIjRKBWrIF4cowhSXP+wC3ouVjhj58il38rapbZQ/CYrcVwMFRYZJy5kg=